modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
   modId="lootbags"
   version="${version}"
   displayName="Lootbags"
   logoFile="icon.png"
   authors="ThatGravyBoat"
   description="Loot Bags"

[[dependencies.lootbags]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.lootbags]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="BOTH"
